import { Gamepad2, Briefcase, Music, Layers, Zap, ShoppingBag, GraduationCap, HeartPulse, Wifi, Car, Home, Globe, Wallet, Dumbbell, Coffee } from 'lucide-react';

export const CURRENCIES = [
  { code: 'UAH', sign: '₴', name: 'Hryvnia' },
  { code: 'USD', sign: '$', name: 'Dollar' },
  { code: 'EUR', sign: '€', name: 'Euro' },
  { code: 'PLN', sign: 'zł', name: 'Złoty' },
  { code: 'KZT', sign: '₸', name: 'Tenge' },
  { code: 'GBP', sign: '£', name: 'Pound' },
  { code: 'JPY', sign: '¥', name: 'Yen' },
  { code: 'CAD', sign: 'C$', name: 'CAD' },
  { code: 'AUD', sign: 'A$', name: 'AUD' },
  { code: 'CHF', sign: 'Fr', name: 'Franc' },
  { code: 'CNY', sign: '¥', name: 'Yuan' },
  { code: 'TRY', sign: '₺', name: 'Lira' },
];

export const CURRENCY_CODES = CURRENCIES.map(c => c.code);

export const LANGUAGES = [
  { code: 'UA', name: 'Українська', flag: '🇺🇦' },
  { code: 'EN', name: 'English', flag: '🇺🇸' },
  { code: 'RU', name: 'Русский', flag: 'aq' },
  { code: 'PL', name: 'Polski', flag: '🇵🇱' },
  { code: 'DE', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ES', name: 'Español', flag: '🇪🇸' },
];

export const REGIONS = [
  { value: 'GLOBAL', label: '🌍 Global' },
  { value: 'UA', label: '🇺🇦 Ukraine' },
  { value: 'US', label: '🇺🇸 USA' },
  { value: 'EU', label: '🇪🇺 Europe' },
  { value: 'ASIA', label: '🌏 Asia' },
];

export const APP_THEMES = {
  emerald: { bg: 'bg-emerald-500', text: 'text-emerald-500', border: 'border-emerald-500', hover: 'hover:bg-emerald-500', name: 'Emerald' },
  violet: { bg: 'bg-violet-600', text: 'text-violet-600', border: 'border-violet-600', hover: 'hover:bg-violet-600', name: 'Amethyst' },
  blue: { bg: 'bg-blue-600', text: 'text-blue-600', border: 'border-blue-600', hover: 'hover:bg-blue-600', name: 'Ocean' },
  orange: { bg: 'bg-orange-500', text: 'text-orange-500', border: 'border-orange-500', hover: 'hover:bg-orange-500', name: 'Sunset' },
  rose: { bg: 'bg-rose-500', text: 'text-rose-500', border: 'border-rose-500', hover: 'hover:bg-rose-500', name: 'Rose' },
  cyan: { bg: 'bg-cyan-500', text: 'text-cyan-500', border: 'border-cyan-500', hover: 'hover:bg-cyan-500', name: 'Sky' },
  indigo: { bg: 'bg-indigo-500', text: 'text-indigo-500', border: 'border-indigo-500', hover: 'hover:bg-indigo-500', name: 'Indigo' },
  pink: { bg: 'bg-pink-500', text: 'text-pink-500', border: 'border-pink-500', hover: 'hover:bg-pink-500', name: 'Berry' },
  lime: { bg: 'bg-lime-500', text: 'text-lime-500', border: 'border-lime-500', hover: 'hover:bg-lime-500', name: 'Lime' },
  yellow: { bg: 'bg-yellow-400', text: 'text-yellow-400', border: 'border-yellow-400', hover: 'hover:bg-yellow-400', name: 'Lemon' },
};

export const COLORS = [
  { val: 'bg-rose-500' }, { val: 'bg-orange-500' }, { val: 'bg-amber-400' },
  { val: 'bg-yellow-400' }, { val: 'bg-lime-500' }, { val: 'bg-green-600' },
  { val: 'bg-emerald-500' }, { val: 'bg-teal-500' }, { val: 'bg-cyan-500' },
  { val: 'bg-sky-500' }, { val: 'bg-blue-600' }, { val: 'bg-indigo-500' },
  { val: 'bg-violet-600' }, { val: 'bg-purple-500' }, { val: 'bg-fuchsia-500' },
  { val: 'bg-pink-500' }, { val: 'bg-rose-900' }, { val: 'bg-slate-600' },
  { val: 'bg-zinc-800' }, { val: 'bg-black' }
];

export const CATEGORIES = {
  all: { icon: Layers, label: 'all' },
  entertainment: { icon: Gamepad2, label: 'entertainment' },
  work: { icon: Briefcase, label: 'work' },
  music: { icon: Music, label: 'music' },
  software: { icon: Layers, label: 'software' },
  utilities: { icon: Zap, label: 'utilities' },
  shopping: { icon: ShoppingBag, label: 'shopping' },
  home: { icon: Home, label: 'home' },
  transport: { icon: Car, label: 'transport' },
  health: { icon: Dumbbell, label: 'health' },
  food: { icon: Coffee, label: 'food' },
};

export const PLACEHOLDERS = {
  all: ['Netflix', 'Spotify', 'Youtube', 'Google One'],
  entertainment: ['Netflix', 'Disney+', 'HBO Max', 'Hulu', 'Steam', 'PlayStation Plus', 'Xbox Game Pass', 'Twitch', 'Megogo', 'Sweet.tv'],
  work: ['LinkedIn Premium', 'Zoom', 'Slack', 'Microsoft 365', 'GitHub Copilot', 'Vercel', 'DigitalOcean'],
  music: ['Spotify', 'Apple Music', 'YouTube Music', 'SoundCloud', 'Deezer', 'Tidal', 'Epidemic Sound'],
  software: ['Adobe Creative Cloud', 'Figma', 'Canva', 'Notion', 'ChatGPT Plus', 'Midjourney', 'JetBrains', '1Password'],
  utilities: ['Google One', 'iCloud', 'Dropbox', 'VPN', 'Kyivstar', 'Vodafone', 'Lifecell', 'Internet'],
  shopping: ['Amazon Prime', 'Walmart+', 'eBay', 'AliExpress', 'Rozetka Premium', 'Nova Poshta'],
  home: ['Rent', 'Electricity', 'Water', 'Heating', 'Cleaning Service', 'Security System'],
  transport: ['Uber Pass', 'Bolt', 'Public Transport', 'Car Insurance', 'Fuel', 'Parking'],
  health: ['Gym Membership', 'Headspace', 'Calm', 'Flo', 'Strava', 'MyFitnessPal', 'Health Insurance'],
  food: ['Glovo Prime', 'Uber Eats', 'Bolt Food', 'HelloFresh', 'Coffee Subscription']
};

export const SERVICES_DB = { GLOBAL: [], UA: [], EU: [] };

export const TRANSLATIONS = {
  UA: { 
    appName: 'SubsTracker', dashboard: 'Головна', calendar: 'Календар', analytics: 'Аналітика', budget: 'Бюджет', settings: 'Налаштування', 
    totalMonth: 'Разом на місяць', add: 'Додати', edit: 'Редагувати', delete: 'Видалити', save: 'Зберегти', 
    namePlace: 'Назва сервісу...', cost: 'Вартість', date: 'Дата оплати', period: 'Період', monthly: 'Щомісяця', yearly: 'Щорічно', 
    budgetTitle: 'Планування бюджету', budgetInput: 'Введіть ваш баланс', budgetResult: 'Вистачить на', months: 'міс.', daysLeft: 'дн.', 
    empty: 'Поки що тут пусто', theme: 'Вигляд', light: 'Світла', dark: 'Темна', currency: 'Валюта', region: 'Регіон', lang: 'Мова', 
    login: 'Вхід', register: 'Реєстрація', loginBtn: 'Увійти', logout: 'Вийти', export: 'Експорт даних', import: 'Імпорт даних', dataMgmt: 'Управління даними', 
    errorPass: 'Невірний пароль', genericError: 'Помилка', chooseAcc: 'Оберіть акаунт', createAcc: 'Створити акаунт', addAcc: 'Додати акаунт', back: 'Назад',
    welcome: 'З поверненням', trial: 'Пробний період', trialLabel: 'Trial', account: 'Мій акаунт', deleteAcc: 'Видалити акаунт', 
    deleteAccConfirm: 'Видалити акаунт і всі дані?', color: 'Акцентний колір',
    darkMode: 'Темний режим', category: 'Категорія', toToday: 'Сьогодні', showInCalendar: 'У календар',
    cats: { all: 'Всі', entertainment: 'Розваги', work: 'Робота', music: 'Музика', software: 'Софт', utilities: 'Послуги', shopping: 'Покупки', home: 'Дім', transport: 'Транспорт', health: 'Здоров\'я', food: 'Їжа', other: 'Інше' },
    cur: { UAH: 'Гривня (₴)', USD: 'Долар ($)', EUR: 'Євро (€)', PLN: 'Злотий (zł)', KZT: 'Тенге (₸)', GBP: 'Фунт (£)', JPY: 'Єна (¥)', CAD: 'Канад. долар (C$)', AUD: 'Австрал. долар (A$)', CHF: 'Франк (Fr)', CNY: 'Юань (¥)', TRY: 'Ліра (₺)' },
    monthNames: ['Січень', 'Лютий', 'Березень', 'Квітень', 'Травень', 'Червень', 'Липень', 'Серпень', 'Вересень', 'Жовтень', 'Листопад', 'Грудень'],
    weekDays: ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    spent: 'Витрати в міс.', remaining: 'Залишок', overBudget: 'Не вистачає',
    syncSlogan: 'Ваші підписки під контролем.',
    search: 'Пошук...',
    catStats: 'Статистика за категоріями',
    cancel: 'Скасувати',
    selectDate: 'Оберіть дату',
    monthsShort: ['Січ', 'Лют', 'Бер', 'Кві', 'Тра', 'Чер', 'Лип', 'Сер', 'Вер', 'Жов', 'Лис', 'Гру'],
    weekDaysShort: ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    subsPlural: ['підписка', 'підписки', 'підписок'], 
    runway: 'Вистачить на',
    forever: 'Назавжди'
  },
  RU: {
    appName: 'SubsTracker', dashboard: 'Главная', calendar: 'Календарь', analytics: 'Аналитика', budget: 'Бюджет', settings: 'Настройки', 
    totalMonth: 'Итого в месяц', add: 'Добавить', edit: 'Редактировать', delete: 'Удалить', save: 'Сохранить', 
    namePlace: 'Название сервиса...', cost: 'Стоимость', date: 'Дата оплаты', period: 'Период', monthly: 'Ежемесячно', yearly: 'Ежегодно', 
    budgetTitle: 'Планирование бюджета', budgetInput: 'Введите ваш баланс', budgetResult: 'Хватит на', months: 'мес.', daysLeft: 'дн.', 
    empty: 'Пока что здесь пусто', theme: 'Внешний вид', light: 'Светлая', dark: 'Темная', currency: 'Валюта', region: 'Регион', lang: 'Язык', 
    login: 'Вход', register: 'Регистрация', loginBtn: 'Войти', logout: 'Выйти', export: 'Экспорт данных', import: 'Импорт данных', dataMgmt: 'Управление данными', 
    errorPass: 'Неверный пароль', genericError: 'Ошибка', chooseAcc: 'Выберите аккаунт', createAcc: 'Создать аккаунт', addAcc: 'Добавить аккаунт', back: 'Назад',
    welcome: 'С возвращением', trial: 'Пробный период', trialLabel: 'Trial', account: 'Мой аккаунт', deleteAcc: 'Удалить аккаунт', 
    deleteAccConfirm: 'Удалить аккаунт и все данные?', color: 'Акцентный цвет',
    darkMode: 'Темный режим', category: 'Категория', toToday: 'Сегодня', showInCalendar: 'В календарь',
    cats: { all: 'Все', entertainment: 'Развлечения', work: 'Работа', music: 'Музыка', software: 'Софт', utilities: 'Услуги', shopping: 'Покупки', home: 'Дом', transport: 'Транспорт', health: 'Здоровье', food: 'Еда', other: 'Другое' },
    cur: { UAH: 'Гривна (₴)', USD: 'Доллар ($)', EUR: 'Евро (€)', PLN: 'Злотый (zł)', KZT: 'Тенге (₸)', GBP: 'Фунт (£)', JPY: 'Йена (¥)', CAD: 'Канад. доллар (C$)', AUD: 'Австрал. доллар (A$)', CHF: 'Франк (Fr)', CNY: 'Юань (¥)', TRY: 'Лира (₺)' },
    monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
    weekDays: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    spent: 'Траты в мес.', remaining: 'Остаток', overBudget: 'Не хватает',
    syncSlogan: 'Ваши подписки под контролем.',
    search: 'Поиск...',
    catStats: 'Статистика по категориям',
    cancel: 'Отмена',
    selectDate: 'Выберите дату',
    monthsShort: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
    weekDaysShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    subsPlural: ['подписка', 'подписки', 'подписок'],
    runway: 'Хватит на',
    forever: 'Навсегда'
  },
  EN: { 
    appName: 'SubsTracker', dashboard: 'Dashboard', calendar: 'Calendar', analytics: 'Analytics', budget: 'Budget', settings: 'Settings', 
    totalMonth: 'Total Monthly', add: 'Add', edit: 'Edit', delete: 'Delete', save: 'Save', 
    namePlace: 'Service name...', cost: 'Cost', date: 'Payment Date', period: 'Period', monthly: 'Monthly', yearly: 'Yearly', 
    budgetTitle: 'Budget Planning', budgetInput: 'Enter your balance', budgetResult: 'Runway', months: 'mo.', daysLeft: 'days', 
    empty: 'It is empty here', theme: 'Appearance', light: 'Light', dark: 'Dark', currency: 'Currency', region: 'Region', lang: 'Language', 
    login: 'Login', register: 'Register', loginBtn: 'Sign In', logout: 'Logout', export: 'Export Data', import: 'Import Data', dataMgmt: 'Data Management', 
    errorPass: 'Wrong password', genericError: 'Error', chooseAcc: 'Choose account', createAcc: 'Create Account', addAcc: 'Add account', back: 'Back',
    welcome: 'Welcome back', trial: 'Free Trial', trialLabel: 'Trial', account: 'My Account', deleteAcc: 'Delete Account', 
    deleteAccConfirm: 'Delete account and all data?', color: 'Accent Color',
    darkMode: 'Dark Mode', category: 'Category', toToday: 'Today', showInCalendar: 'Show in Calendar',
    cats: { all: 'All', entertainment: 'Fun', work: 'Work', music: 'Music', software: 'Soft', utilities: 'Util', shopping: 'Shop', home: 'Home', transport: 'Auto', health: 'Health', food: 'Food', other: 'Other' },
    cur: { UAH: 'Hryvnia (₴)', USD: 'Dollar ($)', EUR: 'Euro (€)', PLN: 'Zloty (zł)', KZT: 'Tenge (₸)', GBP: 'Pound (£)', JPY: 'Yen (¥)', CAD: 'Canadian Dollar (C$)', AUD: 'Australian Dollar (A$)', CHF: 'Franc (Fr)', CNY: 'Yuan (¥)', TRY: 'Lira (₺)' },
    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    weekDays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    spent: 'Monthly burn', remaining: 'Balance', overBudget: 'Deficit',
    syncSlogan: 'Your subscriptions, under control.',
    search: 'Search...',
    catStats: 'Category Statistics',
    cancel: 'Cancel',
    selectDate: 'Select Date',
    monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    weekDaysShort: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    subsPlural: ['subscription', 'subscriptions', 'subscriptions'],
    runway: 'Funds last',
    forever: 'Forever'
  },
  PL: {
    appName: 'SubsTracker', dashboard: 'Pulpit', calendar: 'Kalendarz', analytics: 'Analityka', budget: 'Budżet', settings: 'Ustawienia',
    totalMonth: 'Miesięcznie', add: 'Dodaj', edit: 'Edytuj', delete: 'Usuń', save: 'Zapisz',
    namePlace: 'Nazwa serwisu...', cost: 'Koszt', date: 'Data płatności', period: 'Okres', monthly: 'Miesięcznie', yearly: 'Rocznie',
    budgetTitle: 'Planowanie', budgetInput: 'Twój limit miesięczny', budgetResult: 'Pozostało', months: 'mies.', daysLeft: 'dni',
    empty: 'Pusto tutaj', theme: 'Wygląd', light: 'Jasny', dark: 'Ciemny', currency: 'Waluta', region: 'Region', lang: 'Język',
    login: 'Zaloguj', register: 'Rejestracja', loginBtn: 'Wejdź', logout: 'Wyloguj', export: 'Eksportuj', import: 'Importuj', dataMgmt: 'Dane',
    errorPass: 'Błędne hasło', genericError: 'Błąd', chooseAcc: 'Wybierz konto', createAcc: 'Utwórz', addAcc: 'Dodaj konto', back: 'Wstecz',
    welcome: 'Witaj', trial: 'Okres próbny', trialLabel: 'Trial', account: 'Konto', deleteAcc: 'Usuń konto',
    deleteAccConfirm: 'Usunąć konto i dane?', color: 'Kolor akcentu',
    darkMode: 'Tryb ciemny', category: 'Kategoria', toToday: 'Dzisiaj', showInCalendar: 'Pokaż w kalendarzu',
    cats: { all: 'Wszystkie', entertainment: 'Rozrywka', work: 'Praca', music: 'Muzyka', software: 'Soft', utilities: 'Usługi', shopping: 'Zakupy', home: 'Dom', transport: 'Auto', health: 'Zdrowie', food: 'Jedzenie', other: 'Inne' },
    cur: { UAH: 'Hrywna (₴)', USD: 'Dolar ($)', EUR: 'Euro (€)', PLN: 'Złoty (zł)', KZT: 'Tenge (₸)', GBP: 'Funt (£)', JPY: 'Jen (¥)', CAD: 'Dolar kanadyjski (C$)', AUD: 'Dolar australijski (A$)', CHF: 'Frank (Fr)', CNY: 'Yuan (¥)', TRY: 'Lira (₺)' },
    monthNames: ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień'],
    weekDays: ['Nd', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'So'],
    spent: 'Wydano', remaining: 'Dostępne', overBudget: 'Przekroczenie',
    syncSlogan: 'Twoje subskrypcje pod kontrolą.',
    search: 'Szukaj...',
    catStats: 'Statystyki kategorii',
    cancel: 'Anuluj',
    selectDate: 'Wybierz datę',
    monthsShort: ['Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wrz', 'Paź', 'Lis', 'Gru'],
    weekDaysShort: ['Nd', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'So'],
    subsPlural: ['subskrypcja', 'subskrypcje', 'subskrypcji'],
    runway: 'Wystarczy na',
    forever: 'Na zawsze'
  },
  DE: {
    appName: 'SubsTracker', dashboard: 'Übersicht', calendar: 'Kalender', analytics: 'Analyse', budget: 'Budget', settings: 'Einstellungen',
    totalMonth: 'Monatlich', add: 'Hinzufügen', edit: 'Bearbeiten', delete: 'Löschen', save: 'Speichern',
    namePlace: 'Dienstname...', cost: 'Kosten', date: 'Zahlungsdatum', period: 'Zeitraum', monthly: 'Monatlich', yearly: 'Jährlich',
    budgetTitle: 'Planung', budgetInput: 'Ihr Monatslimit', budgetResult: 'Verbleibend', months: 'Mon.', daysLeft: 'Tage',
    empty: 'Hier ist es leer', theme: 'Aussehen', light: 'Hell', dark: 'Dunkel', currency: 'Währung', region: 'Region', lang: 'Sprache',
    login: 'Anmelden', register: 'Registrieren', loginBtn: 'Einloggen', logout: 'Ausloggen', export: 'Exportieren', import: 'Importieren', dataMgmt: 'Daten',
    errorPass: 'Falsches Passwort', genericError: 'Fehler', chooseAcc: 'Konto wählen', createAcc: 'Erstellen', addAcc: 'Konto hinzufügen', back: 'Zurück',
    welcome: 'Willkommen', trial: 'Testphase', trialLabel: 'Test', account: 'Konto', deleteAcc: 'Konto löschen',
    deleteAccConfirm: 'Alle Daten löschen?', color: 'Akzentfarbe',
    darkMode: 'Dunkelmodus', category: 'Kategorie', toToday: 'Heute', showInCalendar: 'Im Kalender anzeigen',
    cats: { all: 'Alle', entertainment: 'Spaß', work: 'Arbeit', music: 'Musik', software: 'Soft', utilities: 'Dienste', shopping: 'Einkauf', home: 'Haus', transport: 'Auto', health: 'Gesundheit', food: 'Essen', other: 'Andere' },
    cur: { UAH: 'Hrywnja (₴)', USD: 'Dollar ($)', EUR: 'Euro (€)', PLN: 'Zloty (zł)', KZT: 'Tenge (₸)', GBP: 'Pfund (£)', JPY: 'Yen (¥)', CAD: 'Kanad. Dollar (C$)', AUD: 'Austral. Dollar (A$)', CHF: 'Franken (Fr)', CNY: 'Yuan (¥)', TRY: 'Lira (₺)' },
    monthNames: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
    weekDays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
    spent: 'Ausgegeben', remaining: 'Verbleibend', overBudget: 'Über Budget',
    syncSlogan: 'Ihre Abonnements unter Kontrolle.',
    search: 'Suchen...',
    catStats: 'Kategorienstatistiken',
    cancel: 'Abbrechen',
    selectDate: 'Datum wählen',
    monthsShort: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
    weekDaysShort: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
    subsPlural: ['Abonnement', 'Abonnements', 'Abonnements'],
    runway: 'Reicht für',
    forever: 'Für immer'
  },
  ES: {
    appName: 'SubsTracker', dashboard: 'Tablero', calendar: 'Calendario', analytics: 'Analítica', budget: 'Presupuesto', settings: 'Ajustes',
    totalMonth: 'Mensual', add: 'Añadir', edit: 'Editar', delete: 'Borrar', save: 'Guardar',
    namePlace: 'Nombre del servicio...', cost: 'Costo', date: 'Fecha de pago', period: 'Período', monthly: 'Mensual', yearly: 'Anual',
    budgetTitle: 'Planificación', budgetInput: 'Tu límite mensual', budgetResult: 'Restante', months: 'meses', daysLeft: 'días',
    empty: 'Está vacío aquí', theme: 'Apariencia', light: 'Claro', dark: 'Oscuro', currency: 'Moneda', region: 'Región', lang: 'Idioma',
    login: 'Acceso', register: 'Registro', loginBtn: 'Entrar', logout: 'Salir', export: 'Exportar', import: 'Importar', dataMgmt: 'Datos',
    errorPass: 'Contraseña incorrecta', genericError: 'Error', chooseAcc: 'Elegir cuenta', createAcc: 'Crear', addAcc: 'Añadir cuenta', back: 'Atrás',
    welcome: 'Bienvenido', trial: 'Prueba gratis', trialLabel: 'Prueba', account: 'Cuenta', deleteAcc: 'Borrar cuenta',
    deleteAccConfirm: '¿Borrar todos los datos?', color: 'Color de acento',
    darkMode: 'Modo oscuro', category: 'Categoría', toToday: 'Hoy', showInCalendar: 'Mostrar en calendario',
    cats: { all: 'Todo', entertainment: 'Ocio', work: 'Trabajo', music: 'Música', software: 'Soft', utilities: 'Util', shopping: 'Compras', home: 'Casa', transport: 'Auto', health: 'Salud', food: 'Comida', other: 'Otro' },
    cur: { UAH: 'Grivna (₴)', USD: 'Dólar ($)', EUR: 'Euro (€)', PLN: 'Zloty (zł)', KZT: 'Tenge (₸)', GBP: 'Libra (£)', JPY: 'Yen (¥)', CAD: 'Dólar can. (C$)', AUD: 'Dólar aus. (A$)', CHF: 'Franco (Fr)', CNY: 'Yuan (¥)', TRY: 'Lira (₺)' },
    monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
    weekDays: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
    spent: 'Gastado', remaining: 'Restante', overBudget: 'Sobre presupuesto',
    syncSlogan: 'Sus suscripciones bajo control.',
    search: 'Buscar...',
    catStats: 'Estadísticas por categoría',
    cancel: 'Cancelar',
    selectDate: 'Seleccionar fecha',
    monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
    weekDaysShort: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
    subsPlural: ['suscripción', 'suscripciones', 'suscripciones'],
    runway: 'Dura para',
    forever: 'Para siempre'
  }
};